language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

before_script: composer install
script: phpunit
