language: php

php:
  - 7.2
  - 7.3
  - 8.1

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - composer install --no-interaction
  - composer self-update

script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text
